name: Java Selenium CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 24

      # 3️⃣ Install dependencies and build
      - name: Build with Maven
        run: mvn clean install

      # 4️⃣ Run Selenium tests
      - name: Run tests
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
        run: mvn test
